name: release
on:
  release:
    types: [released]
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Dispatch publish-chrome
        uses: aurelien-baudet/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7 # pin@v2
        with:
          workflow: publish-chrome
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: false

      - name: Dispatch publish-firefox
        uses: aurelien-baudet/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7 # pin@v2
        with:
          workflow: publish-firefox
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: false

      - name: Dispatch publish-edge
        uses: aurelien-baudet/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7 # pin@v2
        with:
          workflow: publish-edge
          wait-for-completion: false
